package com.scamslayer.app.ui

import androidx.compose.runtime.Composable
import androidx.compose.runtime.collectAsState
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.StateFlow

/**
 * Centralized localization for ScamSlayer.
 * Usage: L.s.homeTitle, L.s.recordings, etc.
 * Call L.setLanguage("en") to switch.
 */
object L {
    private val _current = MutableStateFlow(Strings.CS)
    val current: StateFlow<Strings> = _current

    val s: Strings get() = _current.value

    fun setLanguage(code: String) {
        _current.value = when (code) {
            "en" -> Strings.EN
            "cs" -> Strings.CS
            else -> {
                val sysLang = java.util.Locale.getDefault().language
                if (sysLang == "cs") Strings.CS else Strings.EN
            }
        }
    }
}

data class Strings(
    val lang: String,
    // Navigation
    val navHome: String,
    val navRecordings: String,
    val navGuide: String,
    // Home
    val appTitle: String,
    val activePersona: String,
    val noPersonaSelected: String,
    val autoForwarding: String,
    val autoForwardingDesc: String,
    val selectPersona: String,
    val refresh: String,
    val noPersonasAvailable: String,
    val createPersona: String,
    // Recordings
    val recordings: String,
    val noRecordingsYet: String,
    val startByRejectingSpam: String,
    val deleteRecording: String,
    val deleteRecordingConfirm: String,
    val cancel: String,
    val delete: String,
    val transcript: String,
    val shareAudio: String,
    val shareTranscript: String,
    val loadingAudio: String,
    val tryAgain: String,
    val renameRecording: String,
    val recordingName: String,
    val unknown: String,
    // Guide
    val guide: String,
    val languageLabel: String,
    val howItWorks: String,
    val step1: String,
    val step2: String,
    val step3: String,
    val step4: String,
    val step5: String,
    val normalCallsNote: String,
    val howForwardingWorks: String,
    val forwardingExplanation: String,
    val ifAutoDoesntWork: String,
    val dialerExplanation: String,
    val importantNote: String,
    val prepaidWarning: String,
    val personas: String,
    val personasDesc: String,
    val customPersonaDesc: String,
    val tips: String,
    val tip1: String,
    val tip2: String,
    val tip3: String,
    val tip4: String,
    val about: String,
    val aboutDesc: String,
    val account: String,
    val phoneNumber: String,
    val changeNumber: String,
    val save: String,
    // Edit persona
    val editPersona: String,
    val personaDetail: String,
    val name: String,
    val personaDescription: String,
    val age: String,
    val gender: String,
    val male: String,
    val female: String,
    val aiInstructions: String,
    val show: String,
    val hide: String,
    val changeInstructionsHint: String,
    val saveAndUse: String,
    val generatingAndSaving: String,
    val deletePersona: String,
    val deletePersonaConfirm: String,
    // Create persona
    val createPersonaTitle: String,
    val nameOptional: String,
    val describePersona: String,
    val generatePersona: String,
    val generating: String,
    val newPortrait: String,
    val newDescription: String,
    val discard: String,
    // Setup
    val setupTitle: String,
    val setupDesc: String,
    val enterPhone: String,
    val phoneHint: String,
    val continueBtn: String,
    // Forwarding failed
    val forwardingFailed: String,
) {
    companion object {
        val CS = Strings(
            lang = "cs",
            navHome = "Domů",
            navRecordings = "Nahrávky",
            navGuide = "Návod",
            appTitle = "ScamSlayer",
            activePersona = "Aktivní persona",
            noPersonaSelected = "Žádná persona nevybrána",
            autoForwarding = "Automatické přesměrování",
            autoForwardingDesc = "Přesměruje odmítnuté hovory přes operátora. Nefunguje u předplacených karet.",
            selectPersona = "Vybrat personu",
            refresh = "Obnovit",
            noPersonasAvailable = "Žádné persony nejsou k dispozici. Zkontrolujte připojení.",
            createPersona = "Vytvořit vlastní personu",
            recordings = "Nahrávky",
            noRecordingsYet = "Zatím žádné nahrávky",
            startByRejectingSpam = "Odmítněte spam hovor a začněte!",
            deleteRecording = "Smazat nahrávku",
            deleteRecordingConfirm = "Opravdu chcete smazat tuto nahrávku?",
            cancel = "Zrušit",
            delete = "Smazat",
            transcript = "Přepis",
            shareAudio = "Sdílet audio",
            shareTranscript = "Sdílet přepis",
            loadingAudio = "Načítám audio...",
            tryAgain = "Zkusit znovu",
            renameRecording = "Přejmenovat nahrávku",
            recordingName = "Název",
            unknown = "Neznámý",
            guide = "Návod",
            languageLabel = "Jazyk person / Persona language",
            howItWorks = "Jak to funguje",
            step1 = "Zapněte \"Automatické přesměrování na AI\" na hlavní obrazovce",
            step2 = "Když vám zavolá podvodník, odmítněte hovor červeným tlačítkem",
            step3 = "Operátor automaticky přesměruje odmítnutý hovor na naši AI",
            step4 = "AI persona zvedne a zdržuje podvodníka na lince",
            step5 = "Poslechněte si nahrávku v záložce Nahrávky",
            normalCallsNote = "Normální hovory zvedejte jako obvykle. Na AI jdou pouze odmítnuté hovory.",
            howForwardingWorks = "Jak funguje přesměrování",
            forwardingExplanation = "Aplikace nastaví přesměrování obsazených/odmítnutých hovorů přes vašeho operátora (USSD kód **67*). Když odmítnete hovor, operátor ho automaticky přepojí na naše AI číslo.",
            ifAutoDoesntWork = "Pokud automatické nastavení nefunguje",
            dialerExplanation = "Na některých telefonech se může otevřít dialer s USSD kódem (vypadá jako **67*číslo#). Stačí stisknout tlačítko Volat pro potvrzení — tím řeknete operátorovi, kam má odmítnuté hovory přesměrovat.",
            importantNote = "Důležité upozornění",
            prepaidWarning = "ScamSlayer funguje pouze pokud váš operátor podporuje přesměrování hovorů. Předplacené karty většiny operátorů přesměrování nepodporují — v takovém případě aplikace nebude fungovat. Pro plnou funkčnost je potřeba paušální tarif.",
            personas = "Persony",
            personasDesc = "Každá persona má unikátní osobnost, hlas a příběh. AI zůstane v roli po celý hovor.",
            customPersonaDesc = "Můžete si vytvořit vlastní personu s popisem, AI portrétem a hlasem podle vašeho výběru.",
            tips = "Tipy",
            tip1 = "Zkoušejte různé persony — některé fungují lépe na určité typy podvodů",
            tip2 = "Čím déle AI udrží podvodníka na lince, tím víc mu plýtvá časem",
            tip3 = "Sdílejte vtipné nahrávky s přáteli a šiřte povědomí",
            tip4 = "Vlastní persony s detailním popisem fungují nejlépe",
            about = "O aplikaci",
            aboutDesc = "AI asistent proti podvodným hovorům. Přesměruje spam hovory na AI, která podvodníka zdržuje a nahrává celý rozhovor.",
            account = "Účet",
            phoneNumber = "Telefonní číslo",
            changeNumber = "Změnit číslo",
            save = "Uložit",
            editPersona = "Upravit personu",
            personaDetail = "Detail persony",
            name = "Jméno",
            personaDescription = "Popis persony",
            age = "Věk",
            gender = "Pohlaví",
            male = "Muž",
            female = "Žena",
            aiInstructions = "Instrukce pro AI",
            show = "Zobrazit",
            hide = "Skrýt",
            changeInstructionsHint = "Pro změnu instrukcí upravte popis persony výše a uložte.",
            saveAndUse = "Uložit a použít",
            generatingAndSaving = "Generuji a ukládám...",
            deletePersona = "Smazat personu",
            deletePersonaConfirm = "Opravdu chcete smazat personu",
            createPersonaTitle = "Vytvořit personu",
            nameOptional = "Jméno (volitelné)",
            describePersona = "Popište svou personu",
            generatePersona = "Vygenerovat personu",
            generating = "Generuji...",
            newPortrait = "Nový portrét",
            newDescription = "Nový popis",
            discard = "Zahodit",
            setupTitle = "ScamSlayer",
            setupDesc = "AI asistent, který zvedne podvodné hovory za vás a zdržuje podvodníky na lince.",
            enterPhone = "Zadejte telefonní číslo",
            phoneHint = "+420...",
            continueBtn = "Pokračovat",
            forwardingFailed = "Přesměrování nefunguje u vašeho tarifu. Zkontrolujte, zda nemáte předplacenou kartu.",
        )

        val EN = Strings(
            lang = "en",
            navHome = "Home",
            navRecordings = "Recordings",
            navGuide = "Guide",
            appTitle = "ScamSlayer",
            activePersona = "Active Persona",
            noPersonaSelected = "No persona selected",
            autoForwarding = "Auto Forwarding",
            autoForwardingDesc = "Forwards rejected calls via your carrier. Does not work with prepaid plans.",
            selectPersona = "Select Persona",
            refresh = "Refresh",
            noPersonasAvailable = "No personas available. Check your connection.",
            createPersona = "Create Custom Persona",
            recordings = "Recordings",
            noRecordingsYet = "No recordings yet",
            startByRejectingSpam = "Reject a spam call to get started!",
            deleteRecording = "Delete Recording",
            deleteRecordingConfirm = "Are you sure you want to delete this recording?",
            cancel = "Cancel",
            delete = "Delete",
            transcript = "Transcript",
            shareAudio = "Share Audio",
            shareTranscript = "Share Transcript",
            loadingAudio = "Loading audio...",
            tryAgain = "Try again",
            renameRecording = "Rename Recording",
            recordingName = "Name",
            unknown = "Unknown",
            guide = "Guide",
            languageLabel = "Persona Language",
            howItWorks = "How It Works",
            step1 = "Turn on \"Auto Forwarding\" on the home screen",
            step2 = "When a scammer calls, reject the call with the red button",
            step3 = "Your carrier automatically forwards the rejected call to our AI",
            step4 = "The AI persona picks up and wastes the scammer's time",
            step5 = "Listen to the recording in the Recordings tab",
            normalCallsNote = "Answer normal calls as usual. Only rejected calls go to AI.",
            howForwardingWorks = "How Forwarding Works",
            forwardingExplanation = "The app sets up call forwarding for busy/rejected calls via your carrier (USSD code **67*). When you reject a call, the carrier automatically redirects it to our AI number.",
            ifAutoDoesntWork = "If automatic setup doesn't work",
            dialerExplanation = "On some phones, the dialer may open with a USSD code (looks like **67*number#). Just press the Call button to confirm — this tells your carrier where to forward rejected calls.",
            importantNote = "Important Notice",
            prepaidWarning = "ScamSlayer only works if your carrier supports call forwarding. Most prepaid plans do not support forwarding — in that case the app will not work. A postpaid plan is required for full functionality.",
            personas = "Personas",
            personasDesc = "Each persona has a unique personality, voice, and backstory. The AI stays in character throughout the call.",
            customPersonaDesc = "Create your own persona with a custom description, AI portrait, and voice of your choice.",
            tips = "Tips",
            tip1 = "Try different personas — some work better for certain types of scams",
            tip2 = "The longer AI keeps the scammer on the line, the more of their time it wastes",
            tip3 = "Share funny recordings with friends and spread awareness",
            tip4 = "Custom personas with detailed descriptions work best",
            about = "About",
            aboutDesc = "AI-powered spam call handler. Forwards spam calls to AI that wastes the scammer's time and records the conversation.",
            account = "Account",
            phoneNumber = "Phone Number",
            changeNumber = "Change Number",
            save = "Save",
            editPersona = "Edit Persona",
            personaDetail = "Persona Detail",
            name = "Name",
            personaDescription = "Persona Description",
            age = "Age",
            gender = "Gender",
            male = "Male",
            female = "Female",
            aiInstructions = "AI Instructions",
            show = "Show",
            hide = "Hide",
            changeInstructionsHint = "To change instructions, edit the persona description above and save.",
            saveAndUse = "Save & Use",
            generatingAndSaving = "Generating & saving...",
            deletePersona = "Delete Persona",
            deletePersonaConfirm = "Are you sure you want to delete persona",
            createPersonaTitle = "Create Persona",
            nameOptional = "Name (optional)",
            describePersona = "Describe your persona",
            generatePersona = "Generate Persona",
            generating = "Generating...",
            newPortrait = "New Portrait",
            newDescription = "New Description",
            discard = "Discard",
            setupTitle = "ScamSlayer",
            setupDesc = "AI assistant that picks up scam calls for you and wastes the scammer's time.",
            enterPhone = "Enter your phone number",
            phoneHint = "+1...",
            continueBtn = "Continue",
            forwardingFailed = "Forwarding doesn't work with your plan. Check if you have a prepaid card.",
        )
    }
}
