package com.scamslayer.app.ui.screens
import com.scamslayer.app.ui.L

import androidx.compose.foundation.layout.Arrangement
import androidx.compose.foundation.layout.Box
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.Row
import androidx.compose.foundation.layout.Spacer
import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.layout.height
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.layout.size
import androidx.compose.foundation.layout.width
import androidx.compose.foundation.rememberScrollState
import androidx.compose.foundation.shape.CircleShape
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.foundation.verticalScroll
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.filled.ArrowBack
import androidx.compose.material.icons.filled.Refresh
import androidx.compose.material.icons.filled.Save
import androidx.compose.material3.Button
import androidx.compose.material3.ButtonDefaults
import androidx.compose.material3.Card
import androidx.compose.material3.CardDefaults
import androidx.compose.material3.CircularProgressIndicator
import androidx.compose.material3.Icon
import androidx.compose.material3.IconButton
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.OutlinedTextField
import androidx.compose.material3.OutlinedTextFieldDefaults
import androidx.compose.material3.Slider
import androidx.compose.material3.SliderDefaults
import androidx.compose.material3.Text
import androidx.compose.material3.TextButton
import androidx.compose.runtime.Composable
import androidx.compose.runtime.collectAsState
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableIntStateOf
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.remember
import androidx.compose.runtime.setValue
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.draw.clip
import androidx.compose.ui.layout.ContentScale
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.dp
import coil.compose.AsyncImage
import com.scamslayer.app.data.model.CustomPersonaDetail
import com.scamslayer.app.data.model.GeneratePersonaResponse
import com.scamslayer.app.ui.MainViewModel
import com.scamslayer.app.ui.theme.ScamOrange
import com.scamslayer.app.ui.theme.ScamRed

@Composable
fun CreatePersonaScreen(
    viewModel: MainViewModel,
    onBack: () -> Unit
) {
    val uiState by viewModel.uiState.collectAsState()

    // Input state
    var name by remember { mutableStateOf("") }
    var description by remember { mutableStateOf("") }
    var age by remember { mutableIntStateOf(50) }
    var isMale by remember { mutableStateOf(true) }

    // Generated result
    var generated by remember { mutableStateOf<GeneratePersonaResponse?>(null) }
    var error by remember { mutableStateOf<String?>(null) }

    // Regeneration loading
    var isRegeneratingPortrait by remember { mutableStateOf(false) }
    var isRegeneratingDescription by remember { mutableStateOf(false) }
    // Force portrait reload
    var portraitKey by remember { mutableIntStateOf(0) }
    // System prompt display
    var personaDetail by remember { mutableStateOf<CustomPersonaDetail?>(null) }
    var systemPromptExpanded by remember { mutableStateOf(false) }

    val scrollState = rememberScrollState()

    val textFieldColors = OutlinedTextFieldDefaults.colors(
        focusedBorderColor = ScamRed,
        unfocusedBorderColor = MaterialTheme.colorScheme.outline,
        focusedLabelColor = ScamRed,
        cursorColor = ScamRed,
        focusedTextColor = MaterialTheme.colorScheme.onSurface,
        unfocusedTextColor = MaterialTheme.colorScheme.onSurface
    )

    Column(
        modifier = Modifier
            .fillMaxSize()
            .verticalScroll(scrollState)
            .padding(horizontal = 20.dp, vertical = 16.dp)
    ) {
        // Header with back button
        Row(verticalAlignment = Alignment.CenterVertically) {
            IconButton(onClick = onBack) {
                Icon(
                    imageVector = Icons.Default.ArrowBack,
                    contentDescription = "Back",
                    tint = MaterialTheme.colorScheme.onBackground
                )
            }
            Spacer(modifier = Modifier.width(8.dp))
            Text(
                text = L.s.createPersonaTitle,
                style = MaterialTheme.typography.headlineLarge,
                color = MaterialTheme.colorScheme.onBackground,
                fontWeight = FontWeight.Bold
            )
        }

        Spacer(modifier = Modifier.height(20.dp))

        if (generated == null) {
            // --- INPUT FORM ---
            Card(
                modifier = Modifier.fillMaxWidth(),
                shape = RoundedCornerShape(12.dp),
                colors = CardDefaults.cardColors(containerColor = MaterialTheme.colorScheme.surface)
            ) {
                Column(modifier = Modifier.padding(16.dp)) {
                    OutlinedTextField(
                        value = name,
                        onValueChange = { name = it },
                        label = { Text(L.s.nameOptional) },
                        placeholder = { Text("") },
                        modifier = Modifier.fillMaxWidth(),
                        singleLine = true,
                        colors = textFieldColors
                    )

                    Spacer(modifier = Modifier.height(12.dp))

                    OutlinedTextField(
                        value = description,
                        onValueChange = { description = it },
                        label = { Text(L.s.describePersona) },
                        placeholder = { Text("") },
                        modifier = Modifier.fillMaxWidth(),
                        minLines = 3,
                        colors = textFieldColors
                    )

                    Spacer(modifier = Modifier.height(16.dp))

                    // Age slider
                    Text(
                        text = "${L.s.age}: $age",
                        style = MaterialTheme.typography.titleSmall,
                        color = MaterialTheme.colorScheme.onSurface
                    )
                    Slider(
                        value = age.toFloat(),
                        onValueChange = { age = it.toInt() },
                        valueRange = 18f..90f,
                        colors = SliderDefaults.colors(
                            thumbColor = ScamRed,
                            activeTrackColor = ScamRed
                        )
                    )

                    Spacer(modifier = Modifier.height(12.dp))

                    // Gender toggle
                    Text(
                        text = L.s.gender,
                        style = MaterialTheme.typography.titleSmall,
                        color = MaterialTheme.colorScheme.onSurface
                    )
                    Spacer(modifier = Modifier.height(4.dp))
                    Row(horizontalArrangement = Arrangement.spacedBy(8.dp)) {
                        Button(
                            onClick = { isMale = true },
                            colors = ButtonDefaults.buttonColors(
                                containerColor = if (isMale) ScamRed else MaterialTheme.colorScheme.surfaceVariant,
                                contentColor = if (isMale) MaterialTheme.colorScheme.onPrimary else MaterialTheme.colorScheme.onSurfaceVariant
                            ),
                            shape = RoundedCornerShape(8.dp)
                        ) {
                            Text(L.s.male)
                        }
                        Button(
                            onClick = { isMale = false },
                            colors = ButtonDefaults.buttonColors(
                                containerColor = if (!isMale) ScamRed else MaterialTheme.colorScheme.surfaceVariant,
                                contentColor = if (!isMale) MaterialTheme.colorScheme.onPrimary else MaterialTheme.colorScheme.onSurfaceVariant
                            ),
                            shape = RoundedCornerShape(8.dp)
                        ) {
                            Text(L.s.female)
                        }
                    }
                }
            }

            Spacer(modifier = Modifier.height(16.dp))

            // Generate button
            Button(
                onClick = {
                    error = null
                    viewModel.generateCustomPersona(
                        description = if (name.isBlank()) description else "Jméno: $name. $description",
                        age = age,
                        gender = if (isMale) "male" else "female",
                        onSuccess = { result ->
                            generated = result
                            viewModel.loadCustomPersonaDetail(result.id) { detail, _ ->
                                if (detail != null) personaDetail = detail
                            }
                        },
                        onError = { msg -> error = msg }
                    )
                },
                modifier = Modifier.fillMaxWidth(),
                enabled = description.isNotBlank() && !uiState.isGeneratingPersona,
                colors = ButtonDefaults.buttonColors(containerColor = ScamRed),
                shape = RoundedCornerShape(12.dp)
            ) {
                if (uiState.isGeneratingPersona) {
                    CircularProgressIndicator(
                        modifier = Modifier.size(20.dp),
                        strokeWidth = 2.dp,
                        color = MaterialTheme.colorScheme.onPrimary
                    )
                    Spacer(modifier = Modifier.width(8.dp))
                    Text(L.s.generating)
                } else {
                    Text(L.s.generatePersona)
                }
            }

            if (error != null) {
                Spacer(modifier = Modifier.height(8.dp))
                Text(
                    text = error!!,
                    color = MaterialTheme.colorScheme.error,
                    style = MaterialTheme.typography.bodySmall
                )
            }
        } else {
            // --- RESULT PREVIEW ---
            val result = generated!!

            // Portrait + Name
            Card(
                modifier = Modifier.fillMaxWidth(),
                shape = RoundedCornerShape(12.dp),
                colors = CardDefaults.cardColors(containerColor = MaterialTheme.colorScheme.surface)
            ) {
                Column(
                    modifier = Modifier.padding(16.dp),
                    horizontalAlignment = Alignment.CenterHorizontally
                ) {
                    if (result.portraitUrl != null) {
                        AsyncImage(
                            model = viewModel.getFullUrl(result.portraitUrl) + "?v=$portraitKey",
                            contentDescription = result.name,
                            modifier = Modifier
                                .size(120.dp)
                                .clip(CircleShape),
                            contentScale = ContentScale.Crop
                        )
                    }

                    Spacer(modifier = Modifier.height(12.dp))

                    Text(
                        text = result.name,
                        style = MaterialTheme.typography.headlineSmall,
                        fontWeight = FontWeight.Bold,
                        color = MaterialTheme.colorScheme.onSurface
                    )
                    Text(
                        text = result.description,
                        style = MaterialTheme.typography.bodyMedium,
                        color = MaterialTheme.colorScheme.onSurfaceVariant
                    )

                    Spacer(modifier = Modifier.height(12.dp))

                    // Regenerate buttons
                    Row(horizontalArrangement = Arrangement.spacedBy(8.dp)) {
                        TextButton(
                            onClick = {
                                isRegeneratingPortrait = true
                                viewModel.regeneratePortrait(result.id) {
                                    isRegeneratingPortrait = false
                                    portraitKey++
                                }
                            },
                            enabled = !isRegeneratingPortrait
                        ) {
                            if (isRegeneratingPortrait) {
                                CircularProgressIndicator(
                                    modifier = Modifier.size(16.dp),
                                    strokeWidth = 2.dp,
                                    color = ScamOrange
                                )
                            } else {
                                Icon(
                                    imageVector = Icons.Default.Refresh,
                                    contentDescription = null,
                                    modifier = Modifier.size(16.dp),
                                    tint = ScamOrange
                                )
                            }
                            Spacer(modifier = Modifier.width(4.dp))
                            Text(L.s.newPortrait, color = ScamOrange)
                        }

                        TextButton(
                            onClick = {
                                isRegeneratingDescription = true
                                viewModel.regenerateDescription(result.id) { updated ->
                                    isRegeneratingDescription = false
                                    if (updated != null) {
                                        generated = result.copy(
                                            name = updated.name,
                                            description = updated.description
                                        )
                                        viewModel.loadCustomPersonaDetail(result.id) { detail, _ ->
                                            if (detail != null) personaDetail = detail
                                        }
                                    }
                                }
                            },
                            enabled = !isRegeneratingDescription
                        ) {
                            if (isRegeneratingDescription) {
                                CircularProgressIndicator(
                                    modifier = Modifier.size(16.dp),
                                    strokeWidth = 2.dp,
                                    color = ScamOrange
                                )
                            } else {
                                Icon(
                                    imageVector = Icons.Default.Refresh,
                                    contentDescription = null,
                                    modifier = Modifier.size(16.dp),
                                    tint = ScamOrange
                                )
                            }
                            Spacer(modifier = Modifier.width(4.dp))
                            Text(L.s.newDescription, color = ScamOrange)
                        }
                    }
                }
            }

            Spacer(modifier = Modifier.height(16.dp))

            // System prompt (read-only)
            if (personaDetail != null) {
                Card(
                    modifier = Modifier.fillMaxWidth(),
                    shape = RoundedCornerShape(12.dp),
                    colors = CardDefaults.cardColors(containerColor = MaterialTheme.colorScheme.surface)
                ) {
                    Column(modifier = Modifier.padding(16.dp)) {
                        Row(
                            verticalAlignment = Alignment.CenterVertically,
                            modifier = Modifier.fillMaxWidth()
                        ) {
                            Text(
                                text = L.s.aiInstructions,
                                style = MaterialTheme.typography.titleSmall,
                                fontWeight = FontWeight.Bold,
                                color = MaterialTheme.colorScheme.onSurface,
                                modifier = Modifier.weight(1f)
                            )
                            TextButton(onClick = { systemPromptExpanded = !systemPromptExpanded }) {
                                Text(
                                    text = if (systemPromptExpanded) L.s.hide else L.s.show,
                                    color = ScamOrange
                                )
                            }
                        }

                        if (systemPromptExpanded) {
                            Spacer(modifier = Modifier.height(8.dp))
                            Text(
                                text = personaDetail?.systemPrompt ?: "",
                                style = MaterialTheme.typography.bodySmall,
                                color = MaterialTheme.colorScheme.onSurfaceVariant,
                                modifier = Modifier.fillMaxWidth()
                            )
                        }
                    }
                }

                Spacer(modifier = Modifier.height(16.dp))
            }

            // Save / Discard buttons
            Row(
                modifier = Modifier.fillMaxWidth(),
                horizontalArrangement = Arrangement.spacedBy(12.dp)
            ) {
                TextButton(
                    onClick = {
                        viewModel.deleteCustomPersona(result.id)
                        onBack()
                    },
                    modifier = Modifier.weight(1f)
                ) {
                    Text(L.s.discard, color = MaterialTheme.colorScheme.error)
                }

                Button(
                    onClick = {
                        viewModel.selectPersona(result.id)
                        onBack()
                    },
                    modifier = Modifier.weight(1f),
                    colors = ButtonDefaults.buttonColors(containerColor = ScamRed),
                    shape = RoundedCornerShape(12.dp)
                ) {
                    Icon(
                        imageVector = Icons.Default.Save,
                        contentDescription = null,
                        modifier = Modifier.size(18.dp)
                    )
                    Spacer(modifier = Modifier.width(4.dp))
                    Text(L.s.saveAndUse)
                }
            }
        }

        Spacer(modifier = Modifier.height(300.dp))
    }
}
